<?php

/**
 * @author      Software Department <developers@rovota.com>
 * @copyright   Copyright (c), Rovota
 * @license     MIT
 */

namespace Rovota\Core\Auth\Enums;

use Rovota\Core\Support\Traits\EnumHelpers;

enum TwoFactorType: string
{
	use EnumHelpers;

	case App = 'app';
	case Email = 'email';
	case Recovery = 'recovery';
	case PhysicalKey = 'key';
	case SMS = 'phone';

	// -----------------

	public function label(): string
	{
		return match ($this) {
			TwoFactorType::App => 'Authenticator app',
			TwoFactorType::Email => 'Email',
			TwoFactorType::Recovery => 'Recovery code',
			TwoFactorType::PhysicalKey => 'Physical key',
			TwoFactorType::SMS => 'SMS',
		};
	}

	public function description(): string
	{
		return match ($this) {
			TwoFactorType::App => 'Verify each sign-in using a code generated by a supported app, like Google Authenticator.',
			TwoFactorType::Email => 'Receive an email with a code to verify each sign-in. Requires a verified email-address.',
			TwoFactorType::Recovery => 'This method will be enabled automatically. When you lose access, you can recover your account using one of the pre-generated codes.',
			TwoFactorType::PhysicalKey => 'Verify your identity using a supported physical key.',
			TwoFactorType::SMS => 'Receive an SMS with a code that can be used to verify each sign-in.',
		};
	}

	public function supports(): array|null
	{
		return match ($this) {
			TwoFactorType::App => ['Google Authenticator', 'Microsoft Authenticator', 'Authy'],
			TwoFactorType::Email => ['Verified email-addresses'],
			default => null,
		};
	}

}